### ISSUE TITLE
Prepare assembly for trimming

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HXE#245]
https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

# TODO

- [ ] hxe\src\Campaign.cs(43,32,44,58):     Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.Stream)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\SFX.cs(346,21,346,67):        Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Campaign.cs(43,32,43,67):     Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\SFX.cs(346,21,346,51):        Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Update.cs(97,31,97,84):       Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Update.cs(97,31,97,64):       Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Update.cs(144,9,144,66):      Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Update.cs(144,9,144,42):      Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\SFX.cs(331,14,331,44):        Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\SFX.cs(334,5,334,28):         Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(80,26,80,61):     Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(81,37,81,67):     Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(46,26,46,61):     Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(47,9,47,43):      Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(53,34,53,70):    Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(54,17,54,51):    Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(66,34,66,70):    Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(67,46,67,76):    Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(318,64,318,131): Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(318,64,318,111): Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(333,42,333,89):  Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(334,25,334,64):  Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Options.cs(512,27,512,67):    Using member 'System.ComponentModel.TypeDescriptor.GetConverter(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Generic TypeConverters may require the generic types to be annotated. For example, NullableConverter requires the underlying type to be DynamicallyAccessedMembers All.
- [ ] hxe\src\Update.cs(144,9,144,66):      Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Update.cs(144,9,144,42):      Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Update.cs(97,31,97,84):       Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Update.cs(97,31,97,64):       Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Campaign.cs(43,32,44,58):     Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.Stream)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Campaign.cs(43,32,43,67):     Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(46,26,46,61):     Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(47,9,47,43):      Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(53,34,53,70):    Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(54,17,54,51):    Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(66,34,66,70):    Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(67,46,67,76):    Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(80,26,80,61):     Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Manifest.cs(81,37,81,67):     Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(318,64,318,131): Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(318,64,318,111): Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(333,42,333,89):  Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\OpenSauce.cs(334,25,334,64):  Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\Options.cs(512,27,512,67):    Using member 'System.ComponentModel.TypeDescriptor.GetConverter(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Generic TypeConverters may require the generic types to be annotated. For example, NullableConverter requires the underlying type to be DynamicallyAccessedMembers All.
- [ ] hxe\src\SFX.cs(331,14,331,44):        Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\SFX.cs(334,5,334,28):         Using member 'System.Xml.Serialization.XmlSerializer.Serialize(System.IO.TextWriter, object?)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.
- [ ] hxe\src\SFX.cs(346,21,346,67):        Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly.
- [ ] hxe\src\SFX.cs(346,21,346,51):        Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(System.Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly.

**Comment by BinToss** [comment]
See
https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained
https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities
